name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t axixatechnologies/nodejs-app .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to docker hub
        run: docker push axixatechnologies/nodejs-app:latest
