name: Deploy Node Application

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: [ubuntu-latest]
  steps:
    # - name: Checkout Source Code
    #   uses: actions/checkout@v4
    - name: Test Job
      run: echo Hello
